# Name of application that calatrava uses to identify a cho client. This is 
# included in the initialHandshake headers. Without it, calatrava will reject the Handshake
name = "cho"

# Cho will tail this file and send the logs to calatrva. This can be the path to 
# any file your application logs to
logSource = "./logs/test_logs.txt"

# Address calatrava is running on
ingestorAddr = "http://localhost:9090"

# Interval at which cho will send logs to calatrava Miliseconds - ms 
interval = "500ms"

# Minimum number of logs before cho sends to calatrava
threshold = 100

